on:
  schedule:
  - cron: "30 4 * * *"

jobs:
  scrape_pbs_releases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Scrape latest Python releases
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        scripts/gen.sh

        untracked_files="$(git ls-files --others --exclude-standard | grep ^share)"
        if [ -z "$untracked_files" ]; then
          exit 0
        fi

        branch_name="$(date '+%Y-%m-%d-%H-%M')"
        git checkout -b "$branch_name"
        git add share
        git commit -m "Newly scraped releases"
        git push origin "$branch_name"

        gh pr create --title="Newly scraped releases as of $(date '+%Y-%m-%d')" --reviewer=tdyas