on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  test_install_python:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup pyenv
      run: |
        git clone https://github.com/pyenv/pyenv.git pyenv-root

        echo "PYENV_ROOT=$(pwd)/pyenv-root" >> "$GITHUB_ENV"
        echo "PATH=$(pwd):${PYENV_ROOT}/bin:\${PATH}" >> "$GITHUB_ENV"

        mkdir -p pyenv-root/plugins
        cd pyenv-root/plugins
        ln -s ../.. pyenv-python-build-standalone
    - name: Install a recent PBS Python into pyenv.
      run: |
        "${PYENV_ROOT}/bin/pyenv" pbs-install 3.12
    - nane: Verify that the PBS Python runs
      run: |
        pbs_python_id="$(pyenv versions --bare | grep ^pbs-3.12)"
        if [ -z "$pbs_python_id" ]; then
           echo "No PBS Python is visible to pyenv." 1>&2
           exit 1
        fi
        "$(pyenv root)/versions/${pbs_python_id}/bin/python3" -c 'print("Hello from PBS.")'
